# Generated by Django 4.1.7 on 2023-05-26 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('costPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sellingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('transactionType', models.CharField(blank=True, max_length=200, null=True)),
                ('transactionDate', models.DateTimeField(blank=True, null=True)),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('productType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.producttype')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.store')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('purchaseDate', models.DateTimeField(blank=True, null=True)),
                ('productType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.producttype')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.store')),
            ],
        ),
    ]
