# Generated by Django 4.0.6 on 2023-02-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_inventory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='costPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sellingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
