# Generated by Django 4.1.7 on 2023-03-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_salesrecord_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
