# Generated by Django 4.0.6 on 2023-02-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_inventory_costprice_inventory_sellingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='costPrice',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sellingPrice',
        ),
    ]
