# Generated by Django 4.0.6 on 2023-02-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_inventory_costprice_remove_inventory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='transactionType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
